# Generated by Django 4.2.1 on 2023-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
