# Generated by Django 4.2.1 on 2023-06-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalityApp', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_condition', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalityApp.patient')),
            ],
        ),
    ]
