# Generated by Django 4.2.1 on 2023-06-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalityApp', '0003_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalityApp.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalityApp.patient')),
            ],
        ),
    ]
