# Generated by Django 4.2.1 on 2023-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalityApp', '0008_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
